# Generated by Django 5.0.4 on 2024-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmodel_created_at_bookmodel_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='books-images'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='ebook',
            field=models.FileField(blank=True, null=True, upload_to='ebooks'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='pages',
            field=models.IntegerField(),
        ),
    ]
